# Generated by Django 4.2 on 2023-05-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_school_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='categories',
        ),
        migrations.AlterField(
            model_name='school',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='my_app.town', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='school',
            name='categories',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.category', verbose_name='Categories'),
            preserve_default=False,
        ),
    ]
