# Generated by Django 4.2 on 2023-05-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_school_categories_alter_school_town_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='additionally_phone',
            new_name='additionalPhone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='my_app.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='my_app.category', verbose_name='Categories'),
        ),
    ]
