# Generated by Django 4.2 on 2023-05-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_additionally_phone_contact_additionalphone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='school',
        ),
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='place',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='my_app.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='my_app.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='school',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town', to='my_app.town', verbose_name='City'),
        ),
    ]
