# Generated by Django 4.2 on 2023-05-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_contact_school_contact_image_contact_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='place',
            new_name='school',
        ),
    ]
